FROM centos

RUN yum update
yum install ruby ruby-devel
# RUN yum install -y epel-release
# RUN yum install -y https://centos7.iuscommunity.org/ius-release.rpm
# RUN yum update

RUN gem sources --remove https://rubygems.org/
RUN gem sources -a https://ruby.taobao.org/
#RUN yum install make gcc gcc-c++ kernel-devel
RUN yum groupinstall "Development Tools"
RUN gem install --no-rdoc --no-ri jekyll
